### ISSUE TITLE
Tag can not be found in Template Gallery inside GTM

### ISSUE THREAD

**Issue by franz-josef-kaiser** [stape-io/hubspot-tag#2]
For some reason, the tag is listed in the public gallery, but can not be found inside GTM

### ~~~~~ Template Gallery Website

![image](https://user-images.githubusercontent.com/387666/176279208-39450c1d-c16a-4b9c-b8ac-76af4112c47f.png)

### ~~~~~ GTM

![image](https://user-images.githubusercontent.com/387666/176279294-249dde00-fc6a-4dba-873a-0027845a57e4.png)

**Comment by Bukashk0zzz** [comment]
Hi,

This tag is for server-side GTM and you try to search for it inside WEB GTM.

**Comment by franz-josef-kaiser** [comment]
@Bukashk0zzz ah, too bad. Would have been great - especially in comparison to the other integrations. Thanks!
