### ISSUE TITLE
Hubspot deprecating API Key usage

### ISSUE THREAD

**Issue by nicedawg** [stape-io/hubspot-tag#3]
First, thanks for providing so many open-source GTM tags, and helpful guides! Your work has been a great asset in my understanding of Server GTM.

I started setting up a hubspot integration with Server GTM, and saw this deprecation notice:
> Please note:
Starting November 30, 2022, HubSpot API keys will no longer be able to be used as an authentication method to access HubSpot APIs. In addition, starting July 15, 2022, you'll no longer be able to create new API keys.
Learn more about [this change](https://developers.hubspot.com/changelog/upcoming-api-key-sunset) and how to [migrate an API key integration](https://developers.hubspot.com/docs/api/migrate-an-api-key-integration-to-a-private-app) to use a private app instead. Rotation of API keys will still be supported to maintain the protection of your data as you migrate to Private Apps.
Upon expiration on November 30, 2022, you will need to use a private app access token or OAuth to authenticate API calls.

It seems this change will necessitate changes to this server tag, and it could be helpful to update guides like [this one](https://stape.io/blog/how-to-connect-website-with-hubspot-using-server-side-tracking) to reflect the changes. 

I'd love to contribute a Pull Request, but I'm a Server GTM n00b so might take a while - but thought I should go ahead and post this issue so others (more adept than me) can be thinking about it too.

**Comment by Bukashk0zzz** [comment]
Hi,

Thanks for the warm word and this issue.
We added task about updating this tag to our backlog.

It's planned to be done by the end of September. 
I know this is not fast, but we have too many plans :)

**Comment by Bukashk0zzz** [comment]
Now template works with private app authentication.

Thanks for the issue.
