### ISSUE TITLE
Tag not showing

### ISSUE THREAD

**Issue by DavidKayser** [stape-io/hubspot-tag#8]
After installing the new template - the tag does not show in the list of tags after creating a new tag of this type.

**Comment by Bukashk0zzz** [comment]
Do you install template manually or from the Gallery?

**Comment by DavidKayser** [comment]
Manually - I didn't think this template was in the gallery.

**Comment by Bukashk0zzz** [comment]
Please try to install it from gallery https://tagmanager.google.com/gallery/#/owners/stape-io/templates/hubspot-tag

**Comment by DavidKayser** [comment]
It's not showing up in the gallery. See image:
![Screen Shot 2023-09-21 at 5 22 05 PM](https://github.com/stape-io/hubspot-tag/assets/11415009/babf0eb3-95bc-48ce-9103-9846fa8fb73b)

**Comment by Bukashk0zzz** [comment]
You try to find this tag in Web GTM but it for Server GTM.
